internet programming languages/Soreva/soreva_app/config/routes.rb
Rails.application.routes.draw do
  get 'new_session', to: 'session#new'
  post 'create_session', to: 'session#create'
  get 'destroy_session', to: 'session#destroy'

  resources :exercises, only: %i[new create show edit update destroy]

  resources :users, only: %i[new index create show edit update destroy]
  post 'user/:id/follow', to: 'users#follow', as: 'follow'
  post 'user/:id/unfollow', to: 'users#unfollow', as: 'unfollow'
  post 'user/:id/accept', to: 'users#accept', as: 'accept'
  post 'user/:id/decline', to: 'users#decline', as: 'decline'
  post 'user/:id/cancel', to: 'users#cancel', as: 'cancel'
  post 'show_updres', to: 'users#show_updres'
  post 'update_results', to: 'users#update_results'
  post 'user_search', to: 'users#search'

  get 'competition', to: 'page#competition'
  root 'page#main'
end

internet programming languages/Soreva/soreva_app/app/views/page/main.html.erb
<header>
    <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark border-bottom">
         <div class="container-fluid">
            <a class="navbar-brand" href="#">Soreva</a>
            <img src="/images/soreva_icon.png" height="40">
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <%= link_to t('global.exercises'), root_path, class: 'nav-link active' %>
                    </li>
                    <li class="nav-item">
                        <%= link_to t('global.users'), users_path, class: 'nav-link' %>
                    </li>
                    <li class="nav-item">
                        <%= link_to t('global.сompetitions'), competition_path, class: 'nav-link' %>
                    </li>
                </ul>
            </div>
            <div>
                <% if current_user.present? %>
                    <%= link_to t('global.my_profile'), user_path(current_user.id), class: 'btn btn-primary' %>
                <% else %>
                    <%= link_to t('global.login'), new_session_path, class: 'btn btn-success' %>
                    <%= link_to t('global.register'), new_user_path, class: 'btn btn-primary ms-3'%>
                <% end %>
            </div>
         </div>
    </nav>
</header>

<% if flash[:notice].present? %>
    <div class="notice-message text-center fs-5 mt-2"><%= notice %></div>
<% end %>
<div class="container overflow-hidden pb-3">
    <div class="row mt-5">
        <div class="col-4">
            <img src="/images/main_pic.png" width="400">
        </div>
        <div class="col-8 text-center">
            <h3><%= t '.welcome' %></h3>
            <p class="text-start fs-4"><%= t '.descript1' %></p>
            <p class="text-start fs-4"><%= t '.descript2' %></p>
            <p class="text-start fs-4"><%= t '.descript3' %></p>
        </div>
    </div>

    <div class="container">
        <div class="row mt-5">
            <h2 class="col-2"><%= t 'global.exercises' %></h2>
            <% if current_user&.admin? %>
                <%= link_to 'Добавить новое упражнение в каталог', new_exercise_path, class: 'btn btn-warning col-4 fs-5' %>
            <% end %>
        </div>
        <% if Exercise.where(exercise_type: 'Грудные мышцы').any? %>
            <div class="row mt-3">
                <button class="btn btn-outline-dark fs-5 col-6 text-start fs-4" type="button" data-bs-toggle="collapse" data-bs-target="#pectoral-muscles" aria-controls="collapseExample">
                    <%= t 'muscle_group.pectoral_muscles' %>
                </button>   
            </div>
            <div class="collapse bg-light bg-gradient border border-top-0 col-6" id="pectoral-muscles">
                <div class="ms-1">
                    <ul type="square" class="fs-5 mt-2">
                        <% Exercise.where(exercise_type: 'Грудные мышцы').each do |exercise| %>
                        <li class="mt-1">
                            <%= link_to "#{exercise.name}", exercise %>
                        </li>
                        <% end %>
                    </ul>
                </div>  
            </div>
        <% end %> 
        <% if Exercise.where(exercise_type: 'Мышцы спины').any? %>
            <div class="row mt-3 pb-1">
                <button class="btn btn-outline-dark fs-5 col-6 text-start fs-4" type="button" data-bs-toggle="collapse" data-bs-target="#back-muscles" aria-controls="collapseExample">
                    <%= t 'muscle_group.back_muscles' %>
                </button>   
            </div>
            <div class="collapse bg-light bg-gradient border border-top-0 col-6" id="back-muscles">    
                <div class="ms-1">
                    <ul type="square" class="fs-5 ms-3 mt-2">
                        <% Exercise.where(exercise_type: 'Мышцы спины').each do |exercise| %>
                        <li class="mt-1">
                            <%= link_to "#{exercise.name}", exercise %>
                        </li>
                        <% end %>
                    </ul>
                </div>
            </div>
        <% end %>
        <% if Exercise.where(exercise_type: 'Трицепс').any? %>
            <div class="row mt-3 pb-1">
                <button class="btn btn-outline-dark fs-5 col-6 text-start fs-4" type="button" data-bs-toggle="collapse" data-bs-target="#triceps" aria-controls="collapseExample">
                    <%= t 'muscle_group.triceps' %>
                </button>   
            </div>
            <div class="collapse bg-light bg-gradient border border-top-0 col-6" id="triceps">
                <div class="mt-3">
                    <ul type="square" class="fs-5 ms-3 mt-2">
                        <% Exercise.where(exercise_type: 'Трицепс').each do |exercise| %>
                        <li class="mt-1">
                            <%= link_to "#{exercise.name}", exercise %>
                        </li>
                        <% end %>
                    </ul>
                </div>
            </div>
        <% end %>
        <% if Exercise.where(exercise_type: 'Бицепс').any? %>
            <div class="row mt-3 pb-1">
                <button class="btn btn-outline-dark fs-5 col-6 text-start fs-4" type="button" data-bs-toggle="collapse" data-bs-target="#biceps" aria-controls="collapseExample">
                    <%= t 'muscle_group.biceps' %>
                </button>   
            </div>
            <div class="collapse bg-light bg-gradient border border-top-0 col-6" id="biceps">
                <div class="ms-1">
                    <ul type="square" class="fs-5 ms-3 mt-2">
                        <% Exercise.where(exercise_type: 'Бицепс').each do |exercise| %>
                        <li class="mt-1">
                            <%= link_to "#{exercise.name}", exercise %>
                        </li>
                        <% end %>
                    </ul>
                </div>
            </div>
        <% end %>
        <% if Exercise.where(exercise_type: 'Мышцы ног').any? %>
            <div class="row mt-3 pb-1">
                <button class="btn btn-outline-dark fs-5 col-6 text-start fs-4" type="button" data-bs-toggle="collapse" data-bs-target="#leg-muscles" aria-controls="collapseExample">
                    <%= t 'muscle_group.leg_muscles' %>
                </button>   
            </div>
            <div class="collapse bg-light bg-gradient border border-top-0 col-6" id="leg-muscles">
                <div class="ms-1">
                    <ul type="square" class="fs-5 ms-3 mt-2">
                        <% Exercise.where(exercise_type: 'Мышцы ног').each do |exercise| %>
                        <li class="mt-1">
                            <%= link_to "#{exercise.name}", exercise %>
                        </li>
                        <% end %>
                    </ul>
                </div>
            </div>
        <% end %>
        <% if Exercise.where(exercise_type: 'Мышцы кора').any? %>
            <div class="row mt-3 pb-1">
                <button class="btn btn-outline-dark fs-5 col-6 text-start fs-4" type="button" data-bs-toggle="collapse" data-bs-target="#abs" aria-controls="collapseExample">
                    <%= t 'muscle_group.сore_muscles' %>
                </button>   
            </div>
            <div class="collapse bg-light bg-gradient border border-top-0 col-6" id="abs">
                <div class="ms-1">
                    <ul type="square" class="fs-5 ms-3 mt-2">
                        <% Exercise.where(exercise_type: 'Мышцы кора').each do |exercise| %>
                        <li class="mt-1">
                            <%= link_to "#{exercise.name}", exercise %>
                        </li>
                        <% end %>
                    </ul>
                </div>   
            </div>
        <% end %>
        <% if Exercise.where(exercise_type: 'Кардио').any? %>
            <div class="row mt-3 pb-1">
                <button class="btn btn-outline-dark fs-5 col-6 text-start fs-4" type="button" data-bs-toggle="collapse" data-bs-target="#cardio" aria-controls="collapseExample">
                    <%= t 'muscle_group.cardio' %>
                </button>   
            </div>
            <div class="collapse bg-light bg-gradient border border-top-0 col-6" id="cardio">
                <div class="ms-1">
                    <ul type="square" class="fs-5 ms-3 mt-2">
                        <% Exercise.where(exercise_type: 'Кардио').each do |exercise| %>
                        <li class="mt-1">
                            <%= link_to "#{exercise.name}", exercise %>
                        </li>
                        <% end %>
                    </ul>
                </div>
            </div>
        <% end %>
    </div>
</div>