internet programming languages/LR 12/lab12_app/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'new_session', to: 'sessions#new'
  get 'create_session', to: 'sessions#create_session'
  get 'exit_session', to: 'sessions#exit'
  root 'lcm_calculator#input'
  get 'show', to: 'lcm_calculator#show'
  get 'new_user', to: 'users#new'
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

internet programming languages/LR 12/lab12_app/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

internet programming languages/LR 12/lab12_app/app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  validates :username, :email, :password_digest, presence: {
    message: '- поле должнo быть заполнены'
  }

  has_secure_password

  def has_password?(submitted_password)
    password_digest == submitted_password
  end

  def self.authenticate(email, submitted_password)
    email
    user = find_by(email:)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end
end

internet programming languages/LR 12/lab12_app/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

internet programming languages/LR 12/lab12_app/app/controllers/lcm_calculator_controller.rb
# frozen_string_literal: true

# Class for LcmCalculator
class LcmCalculatorController < ApplicationController
  before_action :check_user, only: :show
  before_action :validates, only: :show
  def input; end

  def show
    @num1 = params[:number1].to_i
    @num2 = params[:number2].to_i
    @iterations = helpers.evklid @num1.abs, @num2.abs
    @gcd = @iterations.last.first
    @lcm = @num1 * @num2 / @gcd if @gcd != 0
  end

  private

  def check_user
    redirect_to new_session_path if session[:current_user_id].nil?
  end

  def validates
    number1 = params[:number1]
    number2 = params[:number2]
    return if number1&.match(/-?[1-9]+/) && number2&.match(/-?[1-9]+/)

    flash[:alert] = '- поле не должно быть пустым или содержать 0'
    redirect_to input_path
  end
end

internet programming languages/LR 12/lab12_app/app/controllers/sessions_controller.rb
# frozen_string_literal: true

# class for SessionConroller
class SessionsController < ApplicationController
  def new; end

  def create_session
    user = User.authenticate(params[:email], params[:password])
    if user.nil?
      flash[:alert] = '- неверный email или пароль.'
    else
      sign_in user
    end
    redirect_to root_path
  end

  def sign_in(user)
    session[:current_user_id] = user.id
  end

  def sign_out
    session[:current_user_id] = nil
  end

  def exit
    sign_out
    redirect_to :root
  end
end

internet programming languages/LR 12/lab12_app/app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:username, :email, :password_digest)
  end

end

internet programming languages/LR 12/lab12_app/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

internet programming languages/LR 12/lab12_app/app/helpers/lcm_calculator_helper.rb
# frozen_string_literal: true

module LcmCalculatorHelper
  def evklid(num1, num2, itr = [])
    itr.push([num1, num2])
    if num1 != num2
      if num1 > num2
        evklid num1 - num2, num2, itr
      else
        evklid num1, num2 - num1, itr
      end
    end
    itr
  end
end

internet programming languages/LR 12/lab12_app/app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

internet programming languages/LR 12/lab12_app/app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

internet programming languages/LR 12/lab12_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lab12App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

internet programming languages/LR 12/lab12_app/app/views/lcm_calculator/input.html.erb
<h2>Нахождение наибольшего общего делителя и наименьшего общего кратного двух целых чисел</h2>
<% if !flash.empty? %>
<div class = "error_msg">
  <p style = "margin: 1px">Некорректный ввод:</p>
    <% flash.each do |_, msg| %>
            <p style = "margin: 7px 0 3px 10px" > <%= msg %> </p> 
    <% end %>
    <p style = "margin-top: 5px, margin-left:1px">Попробуйте снова.</p>
  </div>
<% end %>
<%= form_with url: show_path, method: :get do |form| %>
    <%= form.label :numbers, "Введите целое число 1: " %>
    <%= form.number_field :number1%> <br>
    <%= form.label :numbers, "Введите целое число 2: " %>
    <%= form.number_field :number2 %> <br>
    <%= form.submit "Submit" %>
  <% end %>
  <br>
<%= link_to 'Log Out', exit_session_path %><br>
<%= link_to " Users list", users_path %>

internet programming languages/LR 12/lab12_app/app/views/lcm_calculator/show.html.erb
<h2>Результаты работы программы:</h2>
<table>
    <tr class = 'main_elements'>
        <th rowspan = "2" style = "border-bottom: 2px solid black"> Введённые данные </th>
        <td> Число 1  </td>
        <td> Число 2 </td>
    </tr>
    <tr class = 'main_elements'>
        <td style = "border-bottom: 2px solid black"> <%= @num1 %> </td>
        <td style = "border-bottom: 2px solid black"> <%= @num2 %> </td>
    </tr>
    <tr>
        <th colspan = "3"> Нахождение наибольшего общего делителя алгоритмом Евклида </th>
    </tr>
    <tr>
        <td> № итерации </td>
        <td> Число 1 </td>
        <td> Число 2 </td>
    </tr>
    <% @iterations.each.with_index(1) do |numbers, index| %>
        <tr id='itr_row'>
            <td> <%= index %> </td>
            <td> <%= numbers[0] %> </td>
            <td> <%= numbers[1] %> </td>
        </tr>
    <% end %>
    <tr>
        <td colspan = "2" style = "text-align: right; border-top: 2px solid black"> Наибольший общий делитель: </td>
        <th id = "gcd" style = "border-top: 2px solid black"> <%= @gcd %> </th>
    </tr>
    <tr>
        <td colspan = "2" style = "text-align: right"> Наименьшее общее кратное: </td>
        <th id = "lcm" > <%= @lcm %> </th>
    </tr>
</table>
<br>
<%= link_to 'Ввести новые значения', root_path%>

internet programming languages/LR 12/lab12_app/app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h3> Некорректный ввод: </h3>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password_digest %>
  </div>

  <div>
    <%= form.submit  %>
  </div>
<% end %>

internet programming languages/LR 12/lab12_app/app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

</div>

internet programming languages/LR 12/lab12_app/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

internet programming languages/LR 12/lab12_app/app/views/users/index.html.erb
<p style="color: green" id="notice"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p id=<%= "#{user.username}" %> >
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>
<p> ________________________ </p>
<%= link_to "New user", new_user_path %>
<br><br>
<%= link_to 'Back to sessions', new_session_path%>

internet programming languages/LR 12/lab12_app/app/views/users/new.html.erb
<h1>New user</h1>
<% if !flash.empty? %>
 <div id = "error_msg">
  <p style = "margin: 1px">Ошибка:</p>
    <% flash.each do |_, msg| %>
            <p style = "margin: 7px 0 3px 10px" id='message' > <%= msg %> </p> 
    <% end %>
    <p style = "margin-top: 0px, margin-left:1px">Попробуйте снова.</p>
  </div>
<% end %>
<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

internet programming languages/LR 12/lab12_app/app/views/users/show.html.erb
<p style="color: green" id='created_user'><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>