internet programming languages/Soreva/soreva_app/config/routes.rb
Rails.application.routes.draw do
  get 'new_session', to: 'session#new'
  post 'create_session', to: 'session#create'
  get 'destroy_session', to: 'session#destroy'

  resources :exercises, only: %i[new create show edit update destroy]

  resources :users, only: %i[new index create show edit update destroy]
  post 'user/:id/follow', to: 'users#follow', as: 'follow'
  post 'user/:id/unfollow', to: 'users#unfollow', as: 'unfollow'
  post 'user/:id/accept', to: 'users#accept', as: 'accept'
  post 'user/:id/decline', to: 'users#decline', as: 'decline'
  post 'user/:id/cancel', to: 'users#cancel', as: 'cancel'
  post 'show_updres', to: 'users#show_updres'
  post 'update_results', to: 'users#update_results'
  post 'user_search', to: 'users#search'

  get 'competition', to: 'page#competition'
  root 'page#main'
end

internet programming languages/Soreva/soreva_app/app/models/user.rb
class User < ApplicationRecord
    followability

    has_one :result

    has_one_attached :avatar

    has_secure_password

    validates_presence_of :username, message: '- введите имя пользователя'
    validates_each :username do |record, attr, value|
        record.errors.add(attr, message: '- имя пользователя может содержать только латинские буквы и цифры') unless value =~ /^[A-z0-9]+$/ 
    end
    validates_length_of :username, minimum: 3, message: '- имя пользователя должно содержать минимум 3 символа'
    validates_length_of :username, maximum: 15, message: '- имя пользователя должно содержать максимум 15 символов'
    validates_uniqueness_of :username, message: '- имя пользователя уже занято'

    validates :avatar, content_type: { in: ['image/png', 'image/jpeg'], message: '- файл формата png или jpeg' }

    validates_presence_of :email, message: '- введите адрес электронной почты'
    validates_uniqueness_of :email, message: '- адрес электрооный почты уже занят'
    
    
    validates_presence_of :password, message: '- введите пароль'
    validates_confirmation_of :password, message: '- пароли должны совпадать'
    validates_length_of :password, minimum: 6, message: '- пароль должен содержать минимум 6 символов'

    validate :check_old_password, on: :update
    
    enum access_level: [:basic, :admin]
    
    attr_accessor :old_password

    def thumbnail
        self.avatar.variant(resize_to_fill: [50, 50]).processed
    end

    def ava
        self.avatar.variant(resize_to_fill: [350, 350]).processed
    end

    def preview
        self.avatar.variant(resize_to_fill: [100, 100]).processed
    end

    def check_old_password
        return if BCrypt::Password.new(password_digest_was).is_password?(old_password)
        
        errors.add :old_password, 'Неверный пароль'
    end

    def unfollow(user)
        followerable_relationships.where(followable_id: user.id).destroy_all
    end
end

internet programming languages/Soreva/soreva_app/app/controllers/users_controller.rb
# frozen_string_literal: true

# Class for UsersController
class UsersController < ApplicationController
  before_action :set_user
  skip_before_action :set_user, only: %i[new create index search show_updres update_results]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      Result.create(user_id: @user.id)
      redirect_to root_path, notice: 'Вы успешно зарегистрированы'
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def index
    @users = User.order(:username)
  end

  def search
    if params[:username_search].present?
      @find_users = []
      User.all.each { |user| @find_users.push(user) if user.username.include?(params[:username_search]) }
    else
      @find_users = User.order(:username)
    end
  end

  def show; end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to user_url(@user), notice: 'Данные успешно изменены'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    log_out if current_user == @user
    @user.destroy
    redirect_to root_path, notice: 'Аккаунт успешно удалён'
  end

  def show_updres; end

  def update_results
    current_user.result.update(
      bench_press_max: params[:bench_press_max],
      bench_press: params[:bench_press],
      pull_ups_max: params[:pull_ups_max],
      pull_ups: params[:pull_ups],
      push_ups_bars_max: params[:push_ups_bars_max],
      push_ups_bars: params[:push_ups_bars],
      run_100m: params[:run_100m],
      barbell_squat: params[:barbell_squat]
    )
    redirect_to user_path(current_user.id)
  end

  def follow
    current_user.send_follow_request_to(@user)
    redirect_to user_path(@user.id)
  end

  def unfollow
    make_it_an_unfriend_request

    current_user.unfollow(@user)
    redirect_to user_path(@user.id)
  end

  def accept
    current_user.accept_follow_request_of(@user)
    make_it_an_friend_request
    redirect_to user_path(current_user.id)
  end

  def decline
    current_user.decline_follow_request_of(@user)
    redirect_to user_path(current_user.id)
  end

  def cancel
    current_user.remove_follow_request_for(@user)
    redirect_to user_path(@user.id)
  end

  private

  def make_it_an_friend_request
    current_user.send_follow_request_to(@user)
    @user.accept_follow_request_of(current_user)
  end

  def make_it_an_unfriend_request
    @user.unfollow(current_user) if @user.mutual_following_with?(current_user)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :avatar, :email, :password, :password_confirmation, :old_password)
  end
end

internet programming languages/Soreva/soreva_app/app/helpers/users_helper.rb
module UsersHelper
end

internet programming languages/Soreva/soreva_app/app/views/users/_edit_form.html.erb
<%= form_with model: user do |form| %>
    <div class="mt-4">
        <% if user.errors[:username].any? %>
            <div class="error-message fst-italic">
                <% user.errors[:username].each do |error| %>
                    <div><%= error %></div>
                <% end %>
            </div>
        <% end %>
        <%= form.label 'Имя пользователя: ' %>
        <%= form.text_field :username, class: 'form-control', placeholder: 'Имя пользователя' %>
    </div>
    <div class="mt-2">
        <% if user.errors[:avatar].any? %>
            <div class="error-message fst-italic">
                <% user.errors[:avatar].each do |error| %>
                    <div><%= error %></div>
                <% end %>
            </div>
        <% end %>
        <%= form.label 'Аватар пользователя: ' %>
        <%= form.file_field :avatar, class: 'form-control' %>
    </div>
    <div class="mt-4">
        <% if user.errors[:email].any? %>
            <div class="error-message fst-italic">
                <% user.errors[:email].each do |error| %>
                    <div><%= error %></div>
                <% end %>
            </div>
        <% end %>
        <%= form.label 'Почта: ' %>
        <%= form.text_field :email, class: 'form-control', placeholder: 'email@example.com' %>
    </div>
    <div class="mt-4">
        <% if user.errors[:password].any? %>
            <div class="error-message fst-italic">
                <% user.errors[:password].each do |error| %>
                    <div><%= error %></div>
                <% end %>
              </div>
        <% end %>
        <%= form.label 'Новый пароль: ' %>
        <%= form.password_field :password, class: 'form-control', placeholder: 'Password' %>
    </div>
    <div class="mt-4">
        <%= form.label 'Повторите новый пароль: ' %>
        <%= form.password_field :password_confirmation, class: 'form-control', placeholder: 'Password' %>
    </div>
    <div class="mt-5">
        <% if user.errors[:old_password].any? %>
            <div class="error-message fst-italic">
                <% user.errors[:old_password].each do |error| %>
                    <div><%= error %></div>
                <% end %>
              </div>
        <% end %>
        <%= form.label 'Подтвердите старый пароль: ' %>
        <%= form.password_field :old_password, class: 'form-control', placeholder: 'Password' %>
    </div>
    <div class="mt-4">
        <%= form.submit value: 'Сохранить измененеия', class: 'btn btn-primary col-md-12'%>
    </div>
<% end %>

internet programming languages/Soreva/soreva_app/app/views/users/_find_users.html.erb
<% if @find_users.any? %>   
    <% @find_users.each do |user| %>
        <div class="col-12 mt-2 pb-1 border-bottom">
            <% if user.avatar.present? %>
                    <%= image_tag user.preview, class: 'offset-4'%>
                <% else %>
                    <img src="/images/default_avatar.png", height="100px", class="offset-4">
                <% end %>
            <%= link_to user.username, user_path(user.id), class: 'fs-2' %>
        </div>
    <% end %>   
<% else %>
    <h4 class='fst-italic text-center mt-5'>Пользователь не найден</h4>
<% end %>

internet programming languages/Soreva/soreva_app/app/views/users/_reg_form.html.erb
<%= form_with model: user do |form| %>
    <div class="mt-4">
        <% if user.errors[:username].any? %>
            <div class="error-message fst-italic">
                <% user.errors[:username].each do |error| %>
                    <div><%= error %></div>
                <% end %>
            </div>
        <% end %>
        <%= form.label (t('user.username') + ':') %>
        <%= form.text_field :username, class: 'form-control', placeholder: t('user.username') %>
    </div>
    <div class="mt-2">
        <% if user.errors[:avatar].any? %>
            <div class="error-message fst-italic">
                <% user.errors[:avatar].each do |error| %>
                    <div><%= error %></div>
                <% end %>
            </div>
        <% end %>
        <%= form.label (t('user.avatar') + ':') %>
        <%= form.file_field :avatar, class: 'form-control' %>
    </div>
    <div class="mt-4">
        <% if user.errors[:email].any? %>
            <div class="error-message fst-italic">
                <% user.errors[:email].each do |error| %>
                    <div><%= error %></div>
                <% end %>
            </div>
        <% end %>
        <%= form.label (t('user.email')) %>
        <%= form.email_field :email, class: 'form-control', placeholder: 'email@example.com' %>
    </div>
    <div class="mt-4">
        <% if user.errors[:password].any? %>
            <div class="error-message fst-italic">
                <% user.errors[:password].each do |error| %>
                    <div><%= error %></div>
                <% end %>
              </div>
        <% end %>
        <%= form.label (t('user.password') + ':') %>
        <%= form.password_field :password, class: 'form-control', placeholder: t('user.password') %>
    </div>
    <div class="mt-4">
        <%= form.label (t('user.password_conf')) %>
        <%= form.password_field :password_confirmation, class: 'form-control', placeholder: t('user.password') %>
    </div>
    <div class="mt-4">
        <%= form.submit value: t('users.new.create'), class: 'btn btn-primary col-md-12'%>
    </div>
<% end %>

internet programming languages/Soreva/soreva_app/app/views/users/_show_updres_form.html.erb
<div class='mb-2'>
    <%= form_with url: update_results_path do |form |%>
        <div>
            <%= form.label 'Жим штанги лёжа(максимальный вес):' %>
            <% if current_user.result.bench_press_max %>
                <%= form.number_field :bench_press_max, class: 'form-control', step: '0.05',  min: '0', placeholder: '(укажите вес в кг)', value: "#{current_user.result.bench_press_max}" %>
            <% else %>
                <%= form.number_field :bench_press_max, class: 'form-control', step: '0.05',  min: '0', placeholder: '(укажите вес в кг)' %>
            <% end %>
        </div>
        <div class='mt-2'>
            <%= form.label 'Жим штанги лёжа(собственный вес):' %>
            <% if current_user.result.bench_press %>
                <%= form.number_field :bench_press, class: 'form-control', min: '0', placeholder: '(укажите вес в кг)',  value: "#{current_user.result.bench_press}" %>
            <% else %>
                <%= form.number_field :bench_press, class: 'form-control', min: '0',  placeholder: '(укажите кол-во повторений)' %>
            <% end %>    
        </div>
        <div class='mt-2'>
            <%= form.label 'Подтягивания(максимальный вес):' %>
            <% if current_user.result.pull_ups_max %>
                <%= form.number_field :pull_ups_max, class: 'form-control', step: '0.05', min: '0', placeholder: '(укажите вес в кг)', value: "#{current_user.result.pull_ups_max}" %>
            <% else %>
                <%= form.number_field :pull_ups_max, class: 'form-control', step: '0.05', min: '0',  placeholder: '(укажите вес в кг)' %>
            <% end %>
        </div>
        <div class='mt-2'>
            <%= form.label 'Подтянивания(собственный вес):' %>
            <% if current_user.result.pull_ups %>
                <%= form.number_field :pull_ups, class: 'form-control', min: '0',  placeholder: '(укажите кол-во повторений)', value: "#{current_user.result.pull_ups}" %>
            <% else %>
                <%= form.number_field :pull_ups, class: 'form-control', min: '0',  placeholder: '(укажите кол-во повторений)' %>
            <% end %>
        </div>
        <div class='mt-2'>
            <%= form.label 'Отжимания на брусьях(максимальный вес):' %>
            <% if current_user.result.push_ups_bars_max%>
                <%= form.number_field :push_ups_bars_max, class: 'form-control', step: '0.05', min: '0',  placeholder: '(укажите вес в кг)', value: "#{current_user.result.push_ups_bars_max}" %>
            <% else %>
                <%= form.number_field :push_ups_bars_max, class: 'form-control', step: '0.05', min: '0',  placeholder: '(укажите вес в кг)' %>
            <% end %>          
        </div>
        <div class='mt-2'>
            <%= form.label 'Отжимания на брусьях(собственный вес):' %>
            <% if current_user.result.push_ups_bars %>
                <%= form.number_field :push_ups_bars, class: 'form-control', min: '0',  placeholder: '(укажите кол-во повторений)', value: "#{current_user.result.push_ups_bars}" %>
            <% else %>
                <%= form.number_field :push_ups_bars, class: 'form-control', min: '0',  placeholder: '(укажите кол-во повторений)' %>
            <% end%>
        </div>
        <div class='mt-2'>
            <%= form.label 'Присед со штангой(максимальный вес):' %>
            <% if current_user.result.barbell_squat %>
                <%= form.number_field :barbell_squat, class: 'form-control', step: '0.05', min: '0', placeholder: '(укажите вес в кг)', value: "#{current_user.result.barbell_squat}" %>
            <% else %>
                <%= form.number_field :barbell_squat, class: 'form-control', step: '0.05', min: '0', placeholder: '(укажите вес в кг)' %>
            <% end %>
        </div>
        <div class='mt-2'>
            <%= form.label 'Бег 100 метров:' %>
            <% if current_user.result.run_100m %>
                <%= form.number_field :run_100m, class: 'form-control', step: '0.01', min: '0',  placeholder: '(укажите время в секундах "8.15")', value: "#{current_user.result.run_100m}" %>
            <% else %>
                <%= form.number_field :run_100m, class: 'form-control', step: '0.01', min: '0',  placeholder: '(укажите время в секундах "8.15")' %>
            <% end %>
        </div>
        <div class='mt-2'>
            <%= form.submit 'Подтвердить изменения', class: 'btn btn-outline-success' %>
            <%= link_to 'Отмена', user_path(current_user), class: 'btn btn-outline-danger ms-2' %>
        </div>
    <% end %>
</div>

internet programming languages/Soreva/soreva_app/app/views/users/edit.html.erb
<div class="container">
    <div class="row mt-5">
        <div class="col-6 offset-3">
            <h3><%= "Редактирование данных пользователя:" %></h3>
                <%= render 'edit_form', user: @user %>
            <%= link_to 'Отмена', @user, class: 'btn btn-danger col-3 mt-3' %>
        </div>
    </div>
</div>

internet programming languages/Soreva/soreva_app/app/views/users/index.html.erb
<header>
    <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark border-bottom">
         <div class="container-fluid">
            <a class="navbar-brand" href="#">Soreva</a>
            <img src="/images/soreva_icon.png" height="40">
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <%= link_to t('global.exercises'), root_path, class: 'nav-link' %>
                    </li>
                    <li class="nav-item">
                        <%= link_to t('global.users'), users_path, class: 'nav-link active' %>
                    </li>
                    <li class="nav-item">
                        <%= link_to t('global.сompetitions'), competition_path, class: 'nav-link' %>
                    </li>
                </ul>
            </div>
            <div>
                <% if current_user.present? %>
                    <%= link_to t('global.my_profile'), user_path(current_user.id), class: 'btn btn-primary' %>
                <% else %>
                    <%= link_to t('global.login'), new_session_path, class: 'btn btn-success' %>
                    <%= link_to t('global.register'), new_user_path, class: 'btn btn-primary ms-3'%>
                <% end %>
            </div>
         </div>
    </nav>
</header>

<%= form_with url: user_search_path do |form| %>
    <div class="row mt-3">
        <div class="col-9 ms-5">
            <%= form.text_field :username_search, placeholder: t('user.username'), class: 'form-control' %>
        </div>
        <div class="col-1">
            <%= form.submit t('.search'), class: 'btn btn-outline-primary fs-6 col-12' %>
        </div>
    </div>
<% end %>
<div id="users">
    <% if @users.any? %>   
        <% @users.each do |user| %>
            <div class="col-12 mt-2 pb-1 border-bottom">
                <% if user.avatar.present? %>
                    <%= image_tag user.preview, class: 'offset-4'%>
                <% else %>
                    <img src="/images/default_avatar.png", height="100px", class="offset-4">
                <% end %>
                <%= link_to user.username, user_path(user.id), class: 'fs-2' %>
            </div>
        <% end %>   
    <% else %>
        <h4 class='fst-italic text-center'>Нет пользователей на сайтеы</h4>
    <% end %>
</div>

internet programming languages/Soreva/soreva_app/app/views/users/new.html.erb
<div class="container mt-5">
  <div class="row mt-5">
    <div class='col-md-6 offset-3'>
      <h2><%= t '.register' %></h2>
      <%= render 'reg_form', user: @user %>
      <%= link_to t('global.back'), root_path, class: 'btn btn-danger col-md-3 mt-3' %>
    </div>
  </div>
</div>

internet programming languages/Soreva/soreva_app/app/views/users/search.turbo_stream.erb
<%= turbo_stream.update 'users', partial: 'find_users' %>

internet programming languages/Soreva/soreva_app/app/views/users/show_updres.turbo_stream.erb
<%= turbo_stream.update 'result', partial: 'show_updres_form' %>